### ISSUE TITLE
ERR_REQUIRE_ESM error

### ISSUE THREAD

**Issue by dougg0k** [sindresorhus/p-all#11]
Hi, 

I installed the latest version, `4.0.0`. I am using ts-node with ESM and it is complaining, I had it for another package which works fine, but not this one.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/p-all/index.js from /app/src/helpers/eventsHelper.ts not supported.
Instead change the require of index.js in /app/src/helpers/eventsHelper.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/app/src/helpers/eventsHelper.ts:7:33)
    at Module.m._compile (/app/node_modules/ts-node/dist/index.js:735:29)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/dist/index.js:737:16)
    at Object.<anonymous> (/app/src/app.ts:25:24)
    at Module.m._compile (/app/node_modules/ts-node/dist/index.js:735:29)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/dist/index.js:737:16)
    at Object.<anonymous> (/app/src/index.ts:6:15)
    at Module.m._compile (/app/node_modules/ts-node/dist/index.js:735:29)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/dist/index.js:737:16)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by dougg0k** [comment]
Forgot to add `"type": "module"` to `package.json`
